// components/shared/tiny-fish.tsx

"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import {
    Fish,
    Play,
    Loader2,
    Globe,
    CheckCircle,
    XCircle,
    Download,
    RefreshCw,
    Sparkles,
    Hash,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";

// One test case generated by AI
type TestCase = {
    id: number;
    name: string;
    goal: string;
};

// Result of one test after agent runs it
type TestResult = {
    id: number;
    name: string;
    status: "completed" | "failed" | "error";
    passed: boolean;
    summary: string;
    details: string;
};

// Full report after all tests run
type Report = {
    url: string;
    summary: {
        total: number;
        passed: number;
        failed: number;
        passRate: string;
    };
    results: TestResult[];
    generatedAt: string;
};

// Steps the page can be in
type Step =
    | "input"       // User entering URL and count
    | "generating"  // AI generating test cases
    | "review"      // User reviewing test cases
    | "running"     // Agents running tests
    | "done";       // Report ready

export function TinyFish() {
    const [step, setStep] = useState<Step>("input");
    const [url, setUrl] = useState<string>("");
    const [count, setCount] = useState<number>(5);
    const [tests, setTests] = useState<TestCase[]>([]);
    const [report, setReport] = useState<Report | null>(null);

    // Generate Test Cases using AI
    const handleGenerate = async () => {
        if (!url) {
            toast.error("Please enter a website URL");
            return;
        }

        setStep("generating");

        try {
            const res = await fetch("/api/tiny-fish/generate-tests", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ url, count }),
            });

            const data = await res.json() as {
                success: boolean;
                tests: TestCase[];
                error?: string;
            };

            if (!res.ok) throw new Error(data.error ?? "Failed to generate");

            setTests(data.tests);
            setStep("review");
            toast.success(`Generated ${data.tests.length} test cases!`);

        } catch (err) {
            toast.error("Failed to generate test cases");
            setStep("input");
            console.error(err);
        }
    };

    // Run All Tests in Parallel 
    const handleRunTests = async () => {
        setStep("running");

        try {
            const res = await fetch("/api/tiny-fish/run-parallel", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ url, tests }),
            });

            const data = await res.json() as Report & { error?: string };

            if (!res.ok) throw new Error(data.error ?? "Failed to run tests");

            setReport(data);
            setStep("done");
            toast.success("All tests completed!");

        } catch (err) {
            toast.error("Failed to run tests");
            setStep("review");
            console.error(err);
        }
    };

    // Download Report as JSON 
    const downloadJSON = () => {
        if (!report) return;

        // Convert report object to formatted JSON text
        const json = JSON.stringify(report, null, 2);

        // Create a file blob and trigger download
        const blob = new Blob([json], { type: "application/json" });
        const link = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = link;
        a.download = `tinyfish-report-${Date.now()}.json`;
        a.click();

        // Clean up the URL object
        URL.revokeObjectURL(link);
        toast.success("JSON report downloaded!");
    };

    // Download Report as PDF using jsPDF 
    const downloadPDF = () => {
        if (!report) return;

        // Create a new PDF document
        const doc = new jsPDF();

        // ── Page settings ──
        const pageWidth = doc.internal.pageSize.getWidth();
        const margin = 20;
        let y = 20; // current Y position on page

        // Title 
        doc.setFontSize(20);
        doc.setFont("helvetica", "bold");
        doc.text("TinyFish Test Report", margin, y);

        // ── Website URL ──
        y += 12;
        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.text(`Website: ${report.url}`, margin, y);

        // ── Date ──
        y += 8;
        doc.text(
            `Generated: ${new Date(report.generatedAt).toLocaleString()}`,
            margin,
            y
        );

        // Divider line 
        y += 8;
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, y, pageWidth - margin, y);

        // Summary Section 
        y += 12;
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Summary", margin, y);

        // Summary boxes
        y += 10;
        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.text(`Total Tests : ${report.summary.total}`, margin, y);

        y += 8;
        // Green color for passed
        doc.setTextColor(22, 163, 74);
        doc.text(`Passed      : ${report.summary.passed}`, margin, y);

        y += 8;
        // Red color for failed
        doc.setTextColor(220, 38, 38);
        doc.text(`Failed      : ${report.summary.failed}`, margin, y);

        y += 8;
        // Black for pass rate
        doc.setTextColor(0, 0, 0);
        doc.text(`Pass Rate   : ${report.summary.passRate}`, margin, y);

        //  Divider line 
        y += 10;
        doc.line(margin, y, pageWidth - margin, y);

        //  Test Results Section 
        y += 12;
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Test Results", margin, y);

        // Loop through each test result
        report.results.forEach((result) => {

            // Add new page if content is near bottom
            if (y > 250) {
                doc.addPage();
                y = 20;
            }

            y += 12;

            // Test name
            doc.setFontSize(11);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(0, 0, 0);
            doc.text(`${result.id}. ${result.name}`, margin, y);

            // Pass/Fail badge next to name
            const badgeText = result.passed ? "PASSED" : "FAILED";
            doc.setFontSize(9);
            if (result.passed) {
                // Green badge for passed
                doc.setTextColor(22, 163, 74);
            } else {
                // Red badge for failed
                doc.setTextColor(220, 38, 38);
            }
            doc.text(badgeText, pageWidth - margin - 20, y);

            // Summary text
            y += 7;
            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(100, 100, 100);

            // Split long text into multiple lines
            const summaryLines = doc.splitTextToSize(
                `Summary: ${result.summary}`,
                pageWidth - margin * 2
            ) as string[];
            doc.text(summaryLines, margin, y);
            y += summaryLines.length * 6;

            // Details text if available
            if (result.details) {
                const detailLines = doc.splitTextToSize(
                    `Details: ${result.details}`,
                    pageWidth - margin * 2
                ) as string[];
                doc.text(detailLines, margin, y);
                y += detailLines.length * 6;
            }

            // Small divider between tests
            doc.setDrawColor(230, 230, 230);
            doc.line(margin, y + 2, pageWidth - margin, y + 2);
        });

        //  Footer 
        y += 15;
        doc.setFontSize(9);
        doc.setTextColor(150, 150, 150);
        doc.setFont("helvetica", "italic");
        doc.text(
            "Generated by TinyFish — Buildify.sh",
            pageWidth / 2,
            y,
            { align: "center" }
        );

        // Save the PDF 
        // This triggers a clean direct download!
        doc.save(`tinyfish-report-${Date.now()}.pdf`);

        toast.success("PDF report downloaded!");
    };

    // Reset everything
    const handleReset = () => {
        setStep("input");
        setUrl("");
        setCount(5);
        setTests([]);
        setReport(null);
    };

    // 
    return (
        <div className="flex flex-col gap-6">

            {/*  Input Form ── */}
            {step === "input" && (
                <div className="flex flex-col gap-4">

                    {/* URL Input */}
                    <div className="space-y-2">
                        <Label htmlFor="url" className="flex items-center gap-2">
                            <Globe className="h-4 w-4" />
                            Website URL to Test
                        </Label>
                        <Input
                            id="url"
                            placeholder="https://example.com"
                            value={url}
                            onChange={(e) => setUrl(e.target.value)}
                        />
                    </div>

                    {/* Number of test cases — USER DECIDES! */}
                    <div className="space-y-2">
                        <Label htmlFor="count" className="flex items-center gap-2">
                            <Hash className="h-4 w-4" />
                            Number of Test Cases
                        </Label>
                        <Input
                            id="count"
                            type="number"
                            min={1}
                            max={20}
                            value={count}
                            onChange={(e) => setCount(Number(e.target.value))}
                        />
                        <p className="text-muted-foreground text-xs">
                            Min: 1 — Max: 20 test cases
                        </p>
                    </div>

                    {/* Generate Button */}
                    <Button
                        onClick={handleGenerate}
                        disabled={!url}
                        className="w-full"
                        size="lg"
                    >
                        <Sparkles className="mr-2 h-4 w-4" />
                        Generate Test Cases with AI
                    </Button>
                </div>
            )}

            {/* Generating ── */}
            {step === "generating" && (
                <div className="flex flex-col items-center gap-4 py-10">
                    <Loader2 className="text-primary h-12 w-12 animate-spin" />
                    <h3 className="font-semibold">AI is generating test cases...</h3>
                    <p className="text-muted-foreground text-sm">
                        Analyzing {url} and creating {count} test cases
                    </p>
                </div>
            )}

            {/*  Review Test Cases  */}
            {step === "review" && (
                <div className="flex flex-col gap-4">
                    <div className="flex items-center justify-between">
                        <Label className="flex items-center gap-2">
                            <Fish className="h-4 w-4" />
                            Generated {tests.length} Test Cases
                        </Label>
                        <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => setStep("input")}
                        >
                            ← Back
                        </Button>
                    </div>

                    {/* Show all test cases */}
                    <div className="flex flex-col gap-2">
                        {tests.map((test) => (
                            <div key={test.id} className="bg-muted rounded-lg p-3">
                                <p className="text-sm font-medium">
                                    {test.id}. {test.name}
                                </p>
                                <p className="text-muted-foreground mt-1 text-xs">
                                    {test.goal}
                                </p>
                            </div>
                        ))}
                    </div>

                    {/* Run All Tests Button */}
                    <Button
                        onClick={handleRunTests}
                        className="w-full"
                        size="lg"
                    >
                        <Play className="mr-2 h-4 w-4" />
                        Run All {tests.length} Tests in Parallel ⚡
                    </Button>
                </div>
            )}

            {/* Running  */}
            {step === "running" && (
                <div className="flex flex-col gap-4">

                    {/* Fish + spinner + text centered */}
                    <div className="flex flex-col items-center gap-3 py-6">
                        <div className="relative">
                            <Fish className="text-primary h-10 w-10" />
                            <Loader2 className="text-primary absolute -right-2 -top-2 h-5 w-5 animate-spin" />
                        </div>
                        <h3 className="text-center font-semibold">
                            Running {tests.length} agents in parallel...
                        </h3>
                        <p className="text-muted-foreground text-center text-sm">
                            All agents are working simultaneously ⚡
                        </p>
                    </div>

                    {/* Test list below */}
                    <div className="flex flex-col gap-2">
                        {tests.map((test) => (
                            <div
                                key={test.id}
                                className="bg-muted flex items-center gap-3 rounded-lg px-4 py-3 text-sm"
                            >
                                <Loader2 className="text-primary h-4 w-4 shrink-0 animate-spin" />
                                <span>{test.name}</span>
                            </div>
                        ))}
                    </div>

                </div>
            )}

            {/*  Report  */}
            {step === "done" && report && (
                <div className="flex flex-col gap-4">

                    {/* Summary Cards */}
                    <div className="grid grid-cols-4 gap-2">
                        <div className="bg-muted rounded-lg p-3 text-center">
                            <p className="text-2xl font-bold">{report.summary.total}</p>
                            <p className="text-muted-foreground text-xs">Total</p>
                        </div>
                        <div className="rounded-lg bg-green-100 p-3 text-center dark:bg-green-900/20">
                            <p className="text-2xl font-bold text-green-600">
                                {report.summary.passed}
                            </p>
                            <p className="text-xs text-green-600">Passed</p>
                        </div>
                        <div className="rounded-lg bg-red-100 p-3 text-center dark:bg-red-900/20">
                            <p className="text-2xl font-bold text-red-600">
                                {report.summary.failed}
                            </p>
                            <p className="text-xs text-red-600">Failed</p>
                        </div>
                        <div className="bg-muted rounded-lg p-3 text-center">
                            <p className="text-2xl font-bold">{report.summary.passRate}</p>
                            <p className="text-muted-foreground text-xs">Pass Rate</p>
                        </div>
                    </div>

                    {/* Individual Test Results */}
                    <div className="flex flex-col gap-2">
                        {report.results.map((result) => (
                            <div key={result.id} className="rounded-lg border p-3">
                                <div className="flex items-center justify-between">
                                    <p className="text-sm font-medium">
                                        {result.id}. {result.name}
                                    </p>
                                    {result.passed ? (
                                        <span className="flex items-center gap-1 text-xs text-green-600">
                                            <CheckCircle className="h-3 w-3" />
                                            Passed
                                        </span>
                                    ) : (
                                        <span className="flex items-center gap-1 text-xs text-red-600">
                                            <XCircle className="h-3 w-3" />
                                            Failed
                                        </span>
                                    )}
                                </div>
                                <p className="text-muted-foreground mt-1 text-xs">
                                    {result.summary}
                                </p>
                            </div>
                        ))}
                    </div>

                    {/* Download Buttons */}
                    <div className="grid grid-cols-2 gap-2">
                        <Button
                            variant="outline"
                            onClick={downloadJSON}
                            className="w-full"
                        >
                            <Download className="mr-2 h-4 w-4" />
                            Download JSON
                        </Button>
                        <Button
                            variant="outline"
                            onClick={downloadPDF}
                            className="w-full"
                        >
                            <Download className="mr-2 h-4 w-4" />
                            Download PDF
                        </Button>
                    </div>

                    {/* Start New Test */}
                    <Button
                        variant="ghost"
                        onClick={handleReset}
                        className="w-full"
                    >
                        <RefreshCw className="mr-2 h-4 w-4" />
                        Start New Test
                    </Button>

                </div>
            )}
        </div>
    );
}
