import { z } from 'zod';

// ============================================================
// ZOD SCHEMA — validates LLM-generated JSON before rendering
// ============================================================

const AnimationTypeSchema = z.enum([
  'fade', 'slide-up', 'slide-down', 'slide-left', 'slide-right',
  'zoom-in', 'zoom-out', 'bounce', 'spring-up', 'spring-scale',
  'typewriter', 'none',
]);

const TransitionTypeSchema = z.enum([
  'fade', 'slide-left', 'slide-right', 'slide-up', 'slide-down', 'wipe', 'none',
]);

const LayoutTypeSchema = z.enum([
  'TITLE', 'TITLE_SUBTITLE', 'STATEMENT', 'BULLET_POINTS',
  'IMAGE_CAPTION', 'SPLIT_LEFT', 'SPLIT_RIGHT', 'THIRDS',
  'LOWER_THIRD', 'FULLSCREEN',
]);

const SlotNameSchema = z.enum([
  'main', 'title', 'subtitle', 'heading', 'bullet',
  'caption', 'text', 'visual', 'col1', 'col2', 'col3', 'lower',
]);

const BackgroundSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('color'), value: z.string() }),
  z.object({
    type: z.literal('gradient'),
    from: z.string(),
    to: z.string(),
    angle: z.number().optional(),
  }),
  z.object({
    type: z.literal('image'),
    url: z.string(),
    objectFit: z.enum(['cover', 'contain', 'fill']).optional(),
    kenBurns: z.enum(['zoom-in', 'zoom-out', 'pan-left', 'pan-right', 'none']).optional(),
  }),
  z.object({ type: z.literal('video'), url: z.string() }),
]);

const BaseElementSchema = {
  slot: SlotNameSchema.optional(),
  animation: AnimationTypeSchema.optional(),
  animationDelay: z.number().optional(),
  animationDuration: z.number().optional(),
  opacity: z.number().min(0).max(1).optional(),
};

const TextElementSchema = z.object({
  type: z.literal('text'),
  text: z.string(),
  fontSize: z.number().min(12).max(200).optional(),
  fontFamily: z.string().optional(),
  fontWeight: z.string().optional(),
  color: z.string().optional(),
  textAlign: z.enum(['left', 'center', 'right']).optional(),
  lineHeight: z.number().optional(),
  letterSpacing: z.number().optional(),
  shadow: z.boolean().optional(),
  background: z.string().optional(),
  padding: z.number().optional(),
  borderRadius: z.number().optional(),
  ...BaseElementSchema,
});

const BulletListElementSchema = z.object({
  type: z.literal('bullet-list'),
  items: z.array(z.string()).min(1).max(8),
  fontSize: z.number().optional(),
  fontFamily: z.string().optional(),
  fontWeight: z.string().optional(),
  color: z.string().optional(),
  bulletColor: z.string().optional(),
  lineHeight: z.number().optional(),
  itemDelay: z.number().optional(),
  shadow: z.boolean().optional(),
  ...BaseElementSchema,
});

const ImageElementSchema = z.object({
  type: z.literal('image'),
  url: z.string(),
  alt: z.string().default('Video asset'),
  objectFit: z.enum(['cover', 'contain', 'fill']).optional(),
  borderRadius: z.number().optional(),
  shadow: z.boolean().optional(),
  border: z.string().optional(),
  ...BaseElementSchema,
});

const ShapeElementSchema = z.object({
  type: z.literal('shape'),
  shape: z.enum(['rectangle', 'circle', 'line', 'triangle']),
  color: z.string().optional(),
  borderRadius: z.number().optional(),
  border: z.string().optional(),
  width: z.union([z.number(), z.string()]).optional(),
  height: z.union([z.number(), z.string()]).optional(),
  ...BaseElementSchema,
});

const DividerElementSchema = z.object({
  type: z.literal('divider'),
  thickness: z.number().optional(),
  color: z.string().optional(),
  width: z.union([z.number(), z.string()]).optional(),
  ...BaseElementSchema,
});

const SceneElementSchema = z.discriminatedUnion('type', [
  TextElementSchema,
  BulletListElementSchema,
  ImageElementSchema,
  ShapeElementSchema,
  DividerElementSchema,
]);

const SceneSchema = z.object({
  id: z.string().optional(),
  layout: LayoutTypeSchema.default('TITLE'),
  durationInFrames: z.number().min(1).default(120),

  /** The narration text generated by the LLM */
  text: z.string().default(""), 
  /** The URL to the audio file, added later by the server */
  ttsUrl: z.string().url().optional(),

  background: BackgroundSchema,
  elements: z.array(SceneElementSchema),
  transition: TransitionTypeSchema.optional(),
  // Default 20 frames (~0.67s at 30fps) — enough to feel smooth without eating content
  transitionDuration: z.number().min(1).max(60).optional().default(20),
  overlay: z.string().optional(),
  overlayOpacity: z.number().min(0).max(1).optional().default(1),
});

export const VideoJsonSchema = z.object({
  duration: z.number().min(1).default(450),
  fps: z.number().optional().default(30),
  width: z.number().optional().default(1280),
  height: z.number().optional().default(720),
  scenes: z.array(SceneSchema).min(1),

  bgmUrl: z.string().url().optional(),
  ttsVolume: z.number().min(0).max(1).default(1),
  musicVolume: z.number().min(0).max(1).default(0.2),

  globalFontFamily: z.string().optional(),
  globalColorScheme: z.object({
    primary: z.string(),
    secondary: z.string(),
    accent: z.string(),
    background: z.string(),
    text: z.string(),
  }).optional(),
});

// ============================================================
// FUZZY MATCHERS — snaps LLM hallucinations to valid Enums
// ============================================================

function mapAnimation(val: any): string {
  if (typeof val !== 'string') return 'fade';
  const s = val.toLowerCase();
  if (s.includes('spring') && s.includes('up')) return 'spring-up';
  if (s.includes('spring') && s.includes('scale')) return 'spring-scale';
  if (s.includes('slide') && s.includes('up')) return 'slide-up';
  if (s.includes('slide') && s.includes('down')) return 'slide-down';
  if (s.includes('slide') && s.includes('left')) return 'slide-left';
  if (s.includes('slide') && s.includes('right')) return 'slide-right';
  if (s.includes('zoom') && s.includes('in')) return 'zoom-in';
  if (s.includes('zoom') && s.includes('out')) return 'zoom-out';
  if (s.includes('type')) return 'typewriter';
  if (s.includes('bounce')) return 'bounce';
  if (s.includes('fade')) return 'fade';
  if (s.includes('none')) return 'none';
  return 'fade';
}

function mapSlot(val: any): string {
  if (typeof val !== 'string') return 'main';
  const s = val.toLowerCase();
  if (s.includes('title') && !s.includes('sub')) return 'title';
  if (s.includes('subtitle')) return 'subtitle';
  if (s.includes('head')) return 'heading';
  if (s.includes('bullet')) return 'bullet';
  if (s.includes('cap')) return 'caption';
  if (s.includes('visual') || s.includes('image')) return 'visual';
  if (s.includes('col1')) return 'col1';
  if (s.includes('col2')) return 'col2';
  if (s.includes('col3')) return 'col3';
  if (s.includes('lower')) return 'lower';
  if (s.includes('text')) return 'text';
  return 'main';
}

function mapTransition(val: any): string {
  if (typeof val !== 'string') return 'fade';
  const s = val.toLowerCase();
  if (s.includes('slide') && s.includes('left')) return 'slide-left';
  if (s.includes('slide') && s.includes('right')) return 'slide-right';
  if (s.includes('slide') && s.includes('up')) return 'slide-up';
  if (s.includes('slide') && s.includes('down')) return 'slide-down';
  if (s.includes('wipe')) return 'wipe';
  if (s.includes('none') || s.includes('cut')) return 'none';
  return 'fade';
}

// ============================================================
// SANITIZER — repairs common LLM mistakes
// ============================================================

function sanitizeBackground(bg: any): any {
  if (!bg || typeof bg !== 'object') {
    return { type: 'color', value: '#111827' };
  }

  // Ensure type exists for discriminated union
  if (!bg.type) bg.type = 'color';

  if (bg.type === 'gradient') {
    bg.from = bg.from ?? bg.start ?? bg.color1 ?? bg.startColor ?? '#0f0c29';
    bg.to = bg.to ?? bg.end ?? bg.color2 ?? bg.endColor ?? '#302b63';
  }

  if (bg.type === 'color') {
    bg.value = bg.value ?? bg.color ?? bg.hex ?? bg.fill ?? '#111827';
  }

  if (bg.type === 'image' || bg.type === 'video') {
    bg.url = bg.url ?? bg.src ?? bg.source ?? '';
  }

  return bg;
}

export function sanitizeVideoJson(raw: any): any {
  if (!raw || typeof raw !== 'object') return raw;

  // Handle bare array fallback
  if (Array.isArray(raw)) {
    const totalFrames = raw.reduce(
      (sum: number, s: any) => sum + (Number(s?.durationInFrames) || 150),
      0,
    );
    raw = {
      duration: totalFrames,
      fps: 30,
      scenes: raw,
    };
  }

  if (!Array.isArray(raw.scenes)) raw.scenes = [];

  raw.scenes = raw.scenes.map((scene: any, index: number) => {
    if (!scene || typeof scene !== 'object') return scene;

    if (scene.durationInFrames === undefined || scene.durationInFrames === null) {
      scene.durationInFrames = 150;
    }

    // Force layout to uppercase string literal match
    if (typeof scene.layout === 'string') {
      scene.layout = scene.layout.toUpperCase().replace(/\s+/g, '_');
    } else if (!scene.layout) {
      scene.layout = index === 0 ? 'TITLE' : 'STATEMENT';
    }

    // Normalize transition
    if (scene.transition !== undefined) {
      scene.transition = mapTransition(scene.transition);
    }

    // Clamp transitionDuration to a sane range
    if (scene.transitionDuration !== undefined) {
      scene.transitionDuration = Math.max(
        1,
        Math.min(60, Number(scene.transitionDuration) || 20),
      );
    }

    scene.background = sanitizeBackground(scene.background);

    if (typeof scene.text !== 'string') {
    // Fallback: use the text from the first 'text' element if scene.text is missing
      const firstTextEl = scene.elements?.find((el: any) => el.type === 'text');
      scene.text = firstTextEl?.text || "";
    }

    if (Array.isArray(scene.elements)) {
      scene.elements = scene.elements.map((el: any) => ({
        ...el,
        slot: mapSlot(el.slot),
        animation: mapAnimation(el.animation),
      }));
    } else {
      scene.elements = [];
    }

    return scene;
  });

  // Recalculate duration accounting for transition overlaps
  // (mirrors getTotalDuration in VideoComposition.tsx)
  const totalDuration = raw.scenes.reduce(
    (sum: number, scene: any, i: number) => {
      const isLast = i === raw.scenes.length - 1;
      const transitionDuration = scene.transitionDuration ?? 20;
      return sum + scene.durationInFrames - (isLast ? 0 : transitionDuration);
    },
    0,
  );

  raw.duration = totalDuration > 0 ? totalDuration : 450;

  return raw;
}

export const validateVideoJson = (raw: unknown) => {
  const sanitized = sanitizeVideoJson(
    typeof raw === 'string' ? JSON.parse(raw) : raw,
  );
  return VideoJsonSchema.safeParse(sanitized);
};